### ISSUE TITLE
Logmein discontinuing free support 

### ISSUE THREAD

**Issue by Teslafly** [random-robbie/hamachi-pi#1]
Logmein is discontinuing free accounts. You can still use your own networks without an account, but not your email as required in the setup for this package. Can I suggest moving to a single network / password based solution instead of what you have now?

**Comment by random-robbie** [comment]
I will have to look at this at some point but at the moment I use a paid account.

**Comment by random-robbie** [comment]
this now looks like they only limit the amount of devices and not stop you using hamachi.
